# Generated by Django 5.1 on 2024-09-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='friendrequest',
            table='friend_requests',
        ),
    ]
